spring:
  application:
    name: Server

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

frontend:
  origin:
    url: ${FRONTEND_URL}

vnPay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${VNPAY_RETURN_URL}
  version: 2.1.0
  command: pay
  order-type: other

jwt:
  secret: ${JWT_SECRET}
  expiration: 600000
  refreshExpiration: 1209600000

app:
  mail:
    from:
      address: ${MAIL_FROM_ADDRESS}
      name: ${MAIL_FROM_NAME}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

hibernate:
  validator:
    fail-fast: false

resilience4j:
  retry:
    instances:
      adminCustomerMetricsRetry:
        max-attempts: 3
        wait-duration: 3s
  ratelimiter:
    instances:
      mailSendRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1m
        timeout-duration: 0
